[versions]
activityKtx = "1.9.3"
agp = "8.3.2"
fragmentKtx = "1.8.5"
kotlin = "1.9.20"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
jetbrainsKotlinJvm = "1.9.0"
hilt = "2.48.1"
retrofit = "2.11.0"
okhttp = "4.12.0"
gson = "2.11.0"
credentials = "1.3.0"
identityGoogleId = "1.1.1"
datastorePreferences = "1.1.3"
timber = "5.0.1"
detekt = "1.23.8"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# https://developer.android.com/jetpack/androidx/releases/hilt?hl=ko
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# https://mvnrepository.com/artifact/com.google.dagger/hilt-core
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }

# https://square.github.io/retrofit/
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

# https://square.github.io/okhttp/
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# https://github.com/google/gson
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# https://developer.android.com/identity/sign-in/credential-manager?hl=ko
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }

# https://developer.android.com/identity/sign-in/credential-manager-siwg?hl=ko
identity-googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "identityGoogleId" }

# https://developer.android.com/jetpack/androidx/releases/datastore?hl=ko
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }

# https://github.com/JakeWharton/timber
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

# https://developer.android.com/jetpack/androidx/releases/hilt?hl=ko
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# detekt https://github.com/detekt/detekt
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[bundles]
network = [
    "retrofit",
    "retrofit-converter-gson",
    "okhttp",
    "okhttp-logging-interceptor",
    "gson"
]